### ISSUE TITLE
setup.sh errors

### ISSUE THREAD

**Issue by courtyardz** [gburlet/robotaba#17]
I get the below errors upon an initial run of your setup script. Do these errors suggest a specific fix to you? Perhaps I have simply installed the wrong Django (I have version 1.7.2)?

~/Dropbox/robotaba> ./setup.sh 
rm: robotaba.db: No such file or directory
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/Users/eck/Dropbox/robotaba/transcribe/models.py", line 24, in <module>
    from scikits.audiolab import wavread
ImportError: No module named scikits.audiolab
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/Users/eck/Dropbox/robotaba/transcribe/models.py", line 24, in <module>
    from scikits.audiolab import wavread
ImportError: No module named scikits.audiolab
~/Dropbox/robotaba> django --version
-bash: django: command not found
~/Dropbox/robotaba> /django
-bash: /django: No such file or directory
~/Dropbox/robotaba>

**Comment by gburlet** [comment]
The polyphonic transcription algorithm that's plugged in requires scikits.audiolab

From your error log:

```
from scikits.audiolab import wavread
ImportError: No module named scikits.audiolab
```

Install this dependency using pip

**Comment by gburlet** [comment]
I'm going to assume this issue is closed.
